name: Deploy to Netlify (dev branch)

on:
  push:
    branches:
      - dev # Trigger only on pushes to the 'dev' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Update this command if your build script is different

      - name: Deploy to Netlify
        uses: netlify/actions-cli@v3
        with:
          auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site-id: ${{ secrets.NETLIFY_SITE_ID }}
          deploy-dir: build # Adjust this if your build output folder is different
